### ISSUE TITLE
Fehlender default Wert erzeugt Fehler

### ISSUE THREAD

**Issue by jommbee** [codefog/contao-faq-tags#1]
Contao 4.9.13
Beim anlegen eines Moduls kommt der Fehler:

"...
General error: 1364 Field 'faq_showTags' doesn't have a default value"
oder:
"...
General error: 1364 Field 'faq_allowTagFiltering' doesn't have a default value
"

**Comment by qzminski** [comment]
Should be fixed in 1.0.1.
